package signing

import (
	"bytes"
	"testing"

	"github.com/ProtonMail/go-crypto/openpgp"
	"github.com/ProtonMail/go-crypto/openpgp/armor"
)

func TestSignerMultiKeyAndExport(t *testing.T) {
	// Generate two dummy GPG keys in-memory
	entity1, err := openpgp.NewEntity("Key One", "Test Key One", "one@example.com", nil)
	if err != nil {
		t.Fatalf("failed to generate key entity 1: %v", err)
	}

	entity2, err := openpgp.NewEntity("Key Two", "Test Key Two", "two@example.com", nil)
	if err != nil {
		t.Fatalf("failed to generate key entity 2: %v", err)
	}

	// Serialize entities to armored private GPG key blocks
	var privKey1 bytes.Buffer
	w1, err := armor.Encode(&privKey1, openpgp.PrivateKeyType, nil)
	if err != nil {
		t.Fatal(err)
	}
	if err := entity1.SerializePrivate(w1, nil); err != nil {
		t.Fatal(err)
	}
	w1.Close()

	var privKey2 bytes.Buffer
	w2, err := armor.Encode(&privKey2, openpgp.PrivateKeyType, nil)
	if err != nil {
		t.Fatal(err)
	}
	if err := entity2.SerializePrivate(w2, nil); err != nil {
		t.Fatal(err)
	}
	w2.Close()

	// Load armored keys into Signer
	signer, err := NewSigner([]string{privKey1.String(), privKey2.String()}, nil)
	if err != nil {
		t.Fatalf("failed to load multiple private keys: %v", err)
	}

	if len(signer.entityList) != 2 {
		t.Fatalf("expected 2 entities loaded, got %d", len(signer.entityList))
	}

	// Sign mock manifest bytes
	manifest := []byte("flatpak-oci-manifest-data-mock-test")
	sigs, err := signer.SignWithAll(manifest)
	if err != nil {
		t.Fatalf("failed to sign manifest with all keys: %v", err)
	}

	if len(sigs) != 2 {
		t.Fatalf("expected 2 signatures, got %d", len(sigs))
	}

	// Verify signatures are different
	if bytes.Equal(sigs[0], sigs[1]) {
		t.Error("signatures generated by different keys should not be identical")
	}

	// Export public armored keyring (for key.asc)
	armoredPub, err := signer.ExportArmoredPublicKeyRing()
	if err != nil {
		t.Fatalf("failed to export armored public keyring: %v", err)
	}
	if armoredPub == "" {
		t.Error("exported armored public keyring is empty")
	}

	// Export public base64 binary keyring (for GPGKey=)
	b64Pub, err := signer.ExportBase64PublicKeyRing()
	if err != nil {
		t.Fatalf("failed to export base64 public keyring: %v", err)
	}
	if b64Pub == "" {
		t.Error("exported base64 public keyring is empty")
	}
}

// generateProtectedKey returns an armored private key whose secret material is
// encrypted with the returned passphrase.
func generateProtectedKey(t *testing.T) (armored, passphrase string) {
	t.Helper()
	pass := "s3cret-pass"
	entity, err := openpgp.NewEntity("Protected", "", "protected@example.com", nil)
	if err != nil {
		t.Fatalf("new entity: %v", err)
	}
	if err := entity.PrivateKey.Encrypt([]byte(pass)); err != nil {
		t.Fatalf("encrypt primary: %v", err)
	}
	for _, sub := range entity.Subkeys {
		if err := sub.PrivateKey.Encrypt([]byte(pass)); err != nil {
			t.Fatalf("encrypt subkey: %v", err)
		}
	}
	var buf bytes.Buffer
	w, err := armor.Encode(&buf, openpgp.PrivateKeyType, nil)
	if err != nil {
		t.Fatal(err)
	}
	if err := entity.SerializePrivateWithoutSigning(w, nil); err != nil {
		t.Fatalf("serialize protected key: %v", err)
	}
	w.Close()
	return buf.String(), pass
}

func TestNewSignerDecryptsProtectedKey(t *testing.T) {
	armored, pass := generateProtectedKey(t)

	signer, err := NewSigner([]string{armored}, []byte(pass))
	if err != nil {
		t.Fatalf("correct passphrase should unlock: %v", err)
	}
	if _, err := signer.SignWithAll([]byte("payload")); err != nil {
		t.Fatalf("signing with unlocked key should succeed: %v", err)
	}

	if _, err := NewSigner([]string{armored}, []byte("wrong")); err == nil {
		t.Fatal("wrong passphrase must fail")
	}

	if _, err := NewSigner([]string{armored}, nil); err == nil {
		t.Fatal("missing passphrase must fail for encrypted key")
	}
}
