package plan

import (
	"fmt"
	"strings"
)

// GenerateGitLabPipeline converts the planned matrix into a GitLab child pipeline YAML.
// Replicates the logic of generate-pipeline.sh.
func GenerateGitLabPipeline(res *PlanResult, buildArm64 bool) string {
	rows := res.MatrixManifest

	// Filter out aarch64 if not buildArm64
	if !buildArm64 {
		var filtered []MatrixRow
		for _, r := range rows {
			if r.Arch != "aarch64" {
				filtered = append(filtered, r)
			}
		}
		rows = filtered
	}

	if len(rows) == 0 {
		return `# Generated by aetherpak plan — do not edit.
stages:
  - build

no-op:
  stage: build
  image: "${AETHERPAK_IMAGE}:${AETHERPAK_IMAGE_TAG}"
  script:
    - echo "No apps changed; nothing to build or publish."
`
	}

	var sb strings.Builder
	sb.WriteString("# Generated by aetherpak plan — do not edit.\n")
	sb.WriteString("include:\n")
	sb.WriteString("  - local: ci/templates.yml\n\n")
	sb.WriteString("stages:\n")
	sb.WriteString("  - build\n")
	sb.WriteString("  - publish\n")
	sb.WriteString("  - pages\n\n")

	var publishJobs []string
	for _, row := range rows {
		slug := slugify(row.AppID)
		bjob := fmt.Sprintf("build:%s-%s", slug, row.Arch)
		pjob := fmt.Sprintf("publish:%s-%s", slug, row.Arch)
		publishJobs = append(publishJobs, pjob)

		// Build Job
		sb.WriteString(fmt.Sprintf("%s:\n", bjob))
		sb.WriteString("  extends: .build\n")
		sb.WriteString("  variables:\n")
		sb.WriteString(fmt.Sprintf("    APP_ID: %q\n", row.AppID))
		sb.WriteString(fmt.Sprintf("    MANIFEST_PATH: %q\n", row.Manifest))
		sb.WriteString(fmt.Sprintf("    ARCH: %q\n", row.Arch))
		sb.WriteString(fmt.Sprintf("    FLATPAK_BRANCH: %q\n", row.Branch))
		if row.Arch == "aarch64" {
			sb.WriteString("  tags:\n")
			sb.WriteString("    - $ARM_RUNNER_TAG\n")
		}
		sb.WriteString("\n")

		// Publish Job
		sb.WriteString(fmt.Sprintf("%s:\n", pjob))
		sb.WriteString("  extends: .publish\n")
		sb.WriteString("  variables:\n")
		sb.WriteString(fmt.Sprintf("    APP_ID: %q\n", row.AppID))
		sb.WriteString(fmt.Sprintf("    ARCH: %q\n", row.Arch))
		sb.WriteString(fmt.Sprintf("    FLATPAK_BRANCH: %q\n", row.Branch))
		sb.WriteString("  needs:\n")
		sb.WriteString(fmt.Sprintf("    - %s\n\n", bjob))
	}

	// Pages Job
	sb.WriteString("pages:\n")
	sb.WriteString("  extends: .pages\n")
	sb.WriteString("  needs:\n")
	for _, pj := range publishJobs {
		sb.WriteString(fmt.Sprintf("    - %s\n", pj))
	}

	return sb.String()
}

// slugify translates App ID (reverse-DNS) into a job-name-safe token.
// Replicates slug() { printf '%s' "$1" | tr -c 'A-Za-z0-9_' '_'; }
func slugify(appID string) string {
	var sb strings.Builder
	for _, r := range appID {
		if (r >= 'a' && r <= 'z') || (r >= 'A' && r <= 'Z') || (r >= '0' && r <= '9') || r == '_' {
			sb.WriteRune(r)
		} else {
			sb.WriteRune('_')
		}
	}
	return sb.String()
}
