name: Release

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  release:
    name: Release Please
    runs-on: ubuntu-latest
    steps:
      - name: Generate App Token
        uses: actions/create-github-app-token@v3
        id: app-token
        with:
          client-id: ${{ vars.AETHERPAK_ACTION_BOT_CLIENT_ID }}
          private-key: ${{ secrets.AETHERPAK_ACTION_BOT_APP_PRIVATE_KEY }}

      - name: Run Release Please
        uses: googleapis/release-please-action@v5
        id: release
        with:
          token: ${{ steps.app-token.outputs.token }}
          config-file: release-please-config.json
          manifest-file: .release-please-manifest.json
